# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99c6afd363146dd7fbac2f0dbd47cc88e75bdf68e381b13763ac14cea95fa730175cb2e73b02f8c1c259ca6db10873125f81a74bbb5ae8293ae963e0e2b5087d

test:
  secret_key_base: 0261335be283f6fb88fd1d9f4339e91c435213c2ffd1acd28441c52269bf2b15b438664ac96bea88f080579dcfef63de1b1121484977a045704ed8d0e95ea157

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
